Add support for Apple's vecLib as math library

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -31,6 +31,11 @@ have_openblas=no
 openblas_path=
 openblas_check=include/openblas_config.h
 
+# Apple vecLib support
+have_veclib=no
+veclib_path=
+veclib_check=Headers/cblas.h
+
 have_kaldi=no
 kaldi_path=
 kaldi_check=src/kaldi.mk
@@ -73,6 +78,7 @@ default_path_list="/usr:/usr/local:/opt:/opt/local"
 default_acmls="acml5.3.1/ifort64_mp"
 default_mkls="CNTKCustomMKL"
 default_openblas=""
+default_veclib="System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework"
 
 # NOTE: Will get compilation errors with cuda-6.0
 default_cudas="cuda-7.5:cuda-7.0:cuda-6.5"
@@ -107,7 +113,7 @@ function find_dir ()
     # Loop over list of tails to search, including empty (just default_path + search file)
     (IFS=":"; for tail in $1 ''
     do
-        for head in $(default_paths)
+        for head in $(default_paths) ''
         do
             [ -n "$tail" ] && search_path="$head/$tail" || search_path="$head"
             if test x$(check_dir "$search_path" "$2") = xyes
@@ -132,6 +138,11 @@ function find_mkl ()
 function find_openblas ()
 {
     find_dir "$default_openblas" "$openblas_check"
+}
+
+function find_veclib ()
+{
+    find_dir "$default_veclib" "$veclib_check"
 }
 
 function find_cuda ()
@@ -222,6 +233,7 @@ function show_help ()
     echo "  --with-mkl[=directory] $(show_default "$(find_mkl)")"
     echo "  --with-mkl-sequential[=directory] $(show_default "$(find_mkl)")"
     echo "  --with-openblas[=directory] (experimental) $(show_default "$(find_openblas)")"
+    echo "  --with-veclib[=directory] $(show_default "$(find_veclib)")"
     echo "  --with-buildtype=(debug|release) $(show_default $default_buildtype)"
     echo "  --with-kaldi[=directory] $(show_default "$(find_kaldi)")"
     echo "  --with-opencv[=directory] $(show_default "$(find_opencv)")"
@@ -451,6 +463,28 @@ do
                 fi
             fi
             ;;
+        --with-veclib*)
+            have_veclib=yes
+            mathlib=veclib
+            if test x"$optarg" = x
+            then
+                veclib_path="$(find_veclib)"
+                if test x"$veclib_path" = x
+                then
+                    echo "Cannot find vecLib directory"
+                    echo "Please specify a value for --with-veclib"
+                    exit 1
+                fi
+            else
+                if test $(check_dir "$optarg" $veclib_check) = yes
+                then
+                    veclib_path="$optarg"
+                else
+                    echo "Invalid vecLib directory $optarg"
+                    exit 1
+                fi
+            fi
+            ;;
         --with-buildtype*)
             have_buildtype=yes
             case $optarg in
@@ -542,8 +576,8 @@ then
     echo Defaulting to --with-buildtype=release
 fi
 
-# If no math library was specified, search for acml and then mkl
-if test x$have_acml = xno && test x$have_mkl = xno && test x$have_openblas = xno
+# If no math library was specified, search for acml, mkl or vecLib (in this order)
+if test x$have_acml = xno && test x$have_mkl = xno && test x$have_openblas = xno && test x$have_veclib = xno
 then
     acml_path="$(find_acml)"
     if test x"$acml_path" = x
@@ -551,9 +585,15 @@ then
         mkl_path="$(find_mkl)"
         if test x"$mkl_path" = x
         then
-            echo "Cannot find a CPU math library."
-            echo "Please specify --with-acml, --with-mkl, --with-mkl-sequential, --with-openblas with a path."
-            exit 1
+            veclib_path="$(find_veclib)"
+            if test x"$veclib_path" = x
+            then
+                echo "Cannot find a CPU math library."
+                echo "Please specify --with-acml, --with-mkl, --with-mkl-sequential, --with-openblas or --with-veclib with a path."
+                exit 1
+            else
+                mathlib=veclib
+            fi
         else
             mathlib=mkl
         fi
